GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Blog 4",
    "author": "Ray Bradbury",
    "url": "http://raysblog.com",
    "likes": 17}